AWSTemplateFormatVersion: '2010-09-09'

Resources:


    BuilderRepository:
        Type: AWS::ECR::Repository
        Properties:
            RepositoryPolicyText:
                Version: "2012-10-17"
                Statement:
                  - Sid: pull
                    Effect: Allow
                    Principal:
                        Service: codebuild.amazonaws.com
                    Action:
                      - "ecr:GetDownloadUrlForLayer"
                      - "ecr:BatchGetImage"
                      - "ecr:BatchCheckLayerAvailability"

    ArtifactStore:
        Type: AWS::S3::Bucket

    SourceStore:
        Type: AWS::S3::Bucket
        Properties:
            VersioningConfiguration:
                Status: Enabled

    PipelineRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    Effect: Allow
                    Action: sts:AssumeRole
                    Principal:
                        Service: codepipeline.amazonaws.com
            Policies:
              - PolicyName: pipeline
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                      - Effect: Allow
                        Action:
                          - codebuild:*
                        Resource:
                          !GetAtt Builder.Arn
                      - Effect: Allow
                        Action:
                          - s3:getObject
                          - s3:GetObjectVersion
                          - s3:GetBucketVersioning
                        Resource:
                          - !GetAtt SourceStore.Arn
                          - !Sub ${SourceStore.Arn}/*
                      - Effect: Allow
                        Action:
                          - s3:GetBucketVersioning
                          - s3:GetObject
                          - s3:GetObjectVersion
                          - s3:PutObject
                        Resource:
                          - !GetAtt ArtifactStore.Arn
                          - !Sub ${ArtifactStore.Arn}/*

    BuilderRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    Effect: Allow
                    Action: sts:AssumeRole
                    Principal:
                        Service: codebuild.amazonaws.com
            Policies:
              - PolicyName: artifact-store
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                      - Effect: Allow
                        Action:
                          - s3:GetObject
                          - s3:GetObjectVersion
                          - s3:PutObject
                        Resource:
                          - !GetAtt ArtifactStore.Arn
                          - !Sub ${ArtifactStore.Arn}/*
                          - arn:aws:s3:::operations-area-frontend-websiteorigin-1rtgo36nz66i0
                          - arn:aws:s3:::operations-area-frontend-websiteorigin-1rtgo36nz66i0/*
                      - Effect: Allow
                        Action:
                          - logs:CreateLogGroup
                          - logs:CreateLogStream
                          - logs:PutLogEvents
                        Resource: "*"



    Pipeline:
        Type: AWS::CodePipeline::Pipeline
        Properties:
            ArtifactStore:
                Location: !Ref ArtifactStore
                Type: S3
            RoleArn: !GetAtt PipelineRole.Arn
            RestartExecutionOnUpdate: false
            Stages:
              - Name: Source
                Actions:
                  - Name: Source
                    ActionTypeId:
                        Category: Source
                        Owner: AWS
                        Version: 1
                        Provider: S3
                    OutputArtifacts:
                        - Name: SourceArtifact
                    Configuration:
                        S3Bucket: !Ref SourceStore
                        S3ObjectKey: master.zip
                    RunOrder: 1
              - Name: Build
                Actions:
                  - Name: Build
                    ActionTypeId:
                        Category: Build
                        Owner: AWS
                        Version: 1
                        Provider: CodeBuild
                    Configuration:
                        ProjectName: !Ref Builder
                    InputArtifacts:
                      - Name: SourceArtifact
                    OutputArtifacts:
                      - Name: BuildArtifact
                    RunOrder: 2

    Builder:
        Type: AWS::CodeBuild::Project
        Properties:
            Artifacts:
                Type: CODEPIPELINE
            Source:
                Type: CODEPIPELINE
            Cache:
                Type: S3
                Location: !Sub ${ArtifactStore}/BUILD_CACHE
            Environment:
                ComputeType: BUILD_GENERAL1_SMALL
                Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${BuilderRepository}
                Type: LINUX_CONTAINER
                EnvironmentVariables:
                  - Name: AWS_DEFAULT_REGION
                    Value: !Ref AWS::Region
                  - Name: CI
                    Value: "true"
            Name: !Sub builder-${AWS::StackName}
            ServiceRole: !Ref BuilderRole

#   # Access for outside deployer i.e. Jenkins
#     DeployerPseudoUser:
#         Type: AWS::IAM::User
#         Properties:
#             Policies:
#               - PolicyName: deployerUser
#                 PolicyDocument:
#                     Version: 2012-10-17
#                     Statement:
#                       - Effect: Allow
#                         Action:
#                           - s3:PutObject
#                         Resource:
#                           - !Sub "${SourceStore.Arn}/*"

#     DeployerPseudoUserAccessKey:
#         Type: "AWS::IAM::AccessKey"
#         Properties:
#             Serial: 1
#             UserName: !Ref DeployerPseudoUser

Outputs:
    BuilderRepository:
        Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${BuilderRepository}
    SourceStore:
        Value: !Ref SourceStore
    ArtifactStore:
        Value: !Ref ArtifactStore
#     DeployerAccessKey:
#         Value: !Ref DeployerPseudoUserAccessKey
#     DeployerSecretAccessKey:
#         Value: !GetAtt DeployerPseudoUserAccessKey.SecretAccessKey






